; Test LSP main loop
(import "src/lsp/main.lisp")

(test-reset)

(test-begin "process-message - initialize request")
(let ((state (make-initial-state)))
  (let ((msg (list (list "jsonrpc" "2.0")
                   (list "id" 1)
                   (list "method" "initialize")
                   (list "params" (list)))))
    ; Note: this will write output to stdout
    (display "Expected output (initialize response): ")
    (let ((result (process-message state msg)))
      (newline)
      (let ((new-state (car result)))
        (let ((should-exit (car (cdr result))))
          (assert-true (state-initialized? new-state) "state initialized")
          (assert-false should-exit "should not exit"))))))
(test-end)

(test-begin "process-message - initialized notification")
(let ((state (state-set (make-initial-state) "initialized" #t)))
  (let ((msg (list (list "jsonrpc" "2.0")
                   (list "method" "initialized")
                   (list "params" (list)))))
    (let ((result (process-message state msg)))
      (let ((new-state (car result)))
        (let ((should-exit (car (cdr result))))
          (assert-true (state-initialized? new-state) "still initialized")
          (assert-false should-exit "should not exit after initialized"))))))
(test-end)

(test-begin "process-message - shutdown request")
(let ((state (state-set (make-initial-state) "initialized" #t)))
  (let ((msg (list (list "jsonrpc" "2.0")
                   (list "id" 2)
                   (list "method" "shutdown")
                   (list "params" 'null))))
    (display "Expected output (shutdown response): ")
    (let ((result (process-message state msg)))
      (newline)
      (let ((new-state (car result)))
        (let ((should-exit (car (cdr result))))
          (assert-true (state-shutdown? new-state) "state shutdown")
          (assert-false should-exit "should not exit after shutdown"))))))
(test-end)

(test-begin "process-message - exit notification")
(let ((state (state-set (make-initial-state) "shutdown" #t)))
  (let ((msg (list (list "jsonrpc" "2.0")
                   (list "method" "exit"))))
    (let ((result (process-message state msg)))
      (let ((should-exit (car (cdr result))))
        (assert-true should-exit "should exit after exit notification")))))
(test-end)

(test-begin "process-message - didOpen notification")
(let ((state (state-set (make-initial-state) "initialized" #t)))
  (let ((msg (list (list "jsonrpc" "2.0")
                   (list "method" "textDocument/didOpen")
                   (list "params" (list (list "textDocument"
                                              (list (list "uri" "file:///test.lisp")
                                                    (list "languageId" "lisp")
                                                    (list "version" 1)
                                                    (list "text" "(+ 1 2)"))))))))
    (let ((result (process-message state msg)))
      (let ((new-state (car result)))
        (assert-eq "(+ 1 2)" (get-document new-state "file:///test.lisp") "document stored")))))
(test-end)

(test-summary)
