; Test LSP go-to-definition
(import "src/lsp/definition.lisp")

(test-reset)

(test-begin "find-definition-location for define function")
(let ((text "(define (square x) (* x x))\n(square 2)"))
  (let ((loc (find-definition-location "file:///test.lisp" text "square")))
    (assert-false (json-null? loc) "location exists")
    (assert-eq "file:///test.lisp" (json-get loc "uri") "location uri")
    (assert-eq 0 (json-get-in loc '("range" "start" "line")) "definition line")
    (assert-eq 9 (json-get-in loc '("range" "start" "character")) "definition column")))
(test-end)

(test-begin "find-definition-location for indented define")
(let ((text "  (define answer 42)\nanswer"))
  (let ((loc (find-definition-location "file:///test.lisp" text "answer")))
    (assert-false (json-null? loc) "location exists")
    (assert-eq 0 (json-get-in loc '("range" "start" "line")) "definition line")
    (assert-eq 10 (json-get-in loc '("range" "start" "character")) "definition column")))
(test-end)

(test-begin "find-definition-location for defmacro")
(let ((text "(defmacro (when test body) (list 'if test body '()))\n(when #t 1)"))
  (let ((loc (find-definition-location "file:///test.lisp" text "when")))
    (assert-false (json-null? loc) "location exists")
    (assert-eq 0 (json-get-in loc '("range" "start" "line")) "macro definition line")
    (assert-eq 11 (json-get-in loc '("range" "start" "character")) "macro definition column")))
(test-end)

(test-begin "find-definition-location for let bindings")
(let ((text "(let ((x 1) (y 2))\n  (+ x y))"))
  (let ((loc (find-definition-location "file:///test.lisp" text "y")))
    (assert-false (json-null? loc) "location exists")
    (assert-eq 0 (json-get-in loc '("range" "start" "line")) "let binding line")
    (assert-eq 13 (json-get-in loc '("range" "start" "character")) "let binding column")))
(test-end)

(test-begin "find-definition-location for multiline let bindings")
(let ((text "(let (\n  (x 1)\n  (y 2))\n  (+ x y))"))
  (let ((loc (find-definition-location "file:///test.lisp" text "y")))
    (assert-false (json-null? loc) "location exists")
    (assert-eq 2 (json-get-in loc '("range" "start" "line")) "let binding line")
    (assert-eq 3 (json-get-in loc '("range" "start" "character")) "let binding column")))
(test-end)

(test-begin "handle-definition-request happy path")
(let ((state0 (state-set (make-initial-state) "initialized" #t)))
  (let ((state1 (set-document state0 "file:///def.lisp" "(define value 1)\n(+ value 2)")))
    (let ((params (list (list "textDocument" (list (list "uri" "file:///def.lisp")))
                        (list "position" (list (list "line" 1) (list "character" 4))))))
      (let ((result (handle-definition-request state1 params 22)))
        (let ((response (car (cdr result))))
          (assert-eq 22 (json-get response "id") "response id")
          (assert-eq 0 (json-get-in response '("result" "range" "start" "line")) "definition line"))))))
(test-end)

(test-begin "handle-definition-request malformed params")
(let ((state (state-set (make-initial-state) "initialized" #t)))
  (let ((result (handle-definition-request state 'null 30)))
    (let ((response (car (cdr result))))
      (assert-eq 'null (json-get response "result") "null params")))
  (let ((result2 (handle-definition-request state '(("textDocument" (("uri" "file:///x.lisp")))) 31)))
    (let ((response2 (car (cdr result2))))
      (assert-eq 'null (json-get response2 "result") "missing position")))
  (let ((result3 (handle-definition-request state
                                            '(("textDocument" (("uri" "file:///x.lisp")))
                                              ("position" (("line" "1") ("character" 0))))
                                            32)))
    (let ((response3 (car (cdr result3))))
      (assert-eq 'null (json-get response3 "result") "non-numeric line returns null"))))
(test-end)

(test-summary)
