; Demonstrate the built-in testing framework

(test-reset)

(test-begin "arithmetic")
(assert-eq 5 (+ 2 3) "addition")
(assert-eq 6 (* 2 3) "multiplication")
(assert-eq 2 (- 5 3) "subtraction")
(assert-eq 3 (/ 9 3) "division")
(assert-true (> 5 3) "greater than")
(assert-true (< 3 5) "less than")
(assert-false (= 3 5) "not equal")
(test-end)

(test-begin "lists")
(assert-eq 1 (car '(1 2 3)) "car")
(assert-eq '(2 3) (cdr '(1 2 3)) "cdr")
(assert-eq 3 (length '(1 2 3)) "length")
(assert-eq '(0 1 2 3) (cons 0 '(1 2 3)) "cons")
(assert-true (null? '()) "null? on empty list")
(assert-false (null? '(1)) "null? on non-empty list")
(assert-true (pair? '(1 2)) "pair? on list")
(test-end)

(test-begin "booleans")
(assert-true #t "true is truthy")
(assert-false #f "false is falsy")
(assert-true (not #f) "not false")
(assert-false (not #t) "not true")
(assert-true (and #t #t) "and both true")
(assert-false (and #t #f) "and one false")
(assert-true (or #f #t) "or one true")
(assert-false (or #f #f) "or both false")
(test-end)

(test-begin "lambdas")
(define square (lambda (x) (* x x)))
(assert-eq 25 (square 5) "square function")
(define add (lambda (a b) (+ a b)))
(assert-eq 7 (add 3 4) "add function")
(test-end)

(test-begin "errors")
(assert-throws (car '()) "car of empty list")
(assert-throws (/ 1 0) "division by zero")
(assert-throws undefined-variable "undefined variable")
(test-end)

(test-begin "try special form")
(define result (try (+ 1 2)))
(assert-eq 'ok (car result) "try success returns ok")
(assert-eq 3 (car (cdr result)) "try success has value")
(define error-result (try (/ 1 0)))
(assert-eq 'error (car error-result) "try error returns error")
(test-end)

(test-summary)
